root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "npm run build:css && templ generate && go build -o ./tmp/main ."
  delay = 1
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules", "static"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "dlv exec --accept-multiclient --headless --listen :2345 --api-version 2 --continue ./tmp/main --"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "js"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[watch]
# Directories and files to watch for changes
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
# Exclude the compiled binary and temporary files
# excludes = ["tmp/", "bin/"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  level = "debug"
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  enabled = true
  proxy_port = 8090
  app_port = 8080

[screen]
  clear_on_rebuild = false
  keep_scroll = true
