services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: split
    ports:
      - "8090:8080"
    restart: unless-stopped
    environment:
      - SPLIT_FX_RATES_API_TOKEN=${SPLIT_FX_RATES_API_TOKEN}
      - SPLIT_DATABASE_URL=./data/split.db
    volumes:
      - ${SPLIT_DB_PATH}/split.db:/app/data/split.db
