// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Styles() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style type=\"text/css\">\n        [x-cloak] { display: none !important; }\n        .icon {\n            width: 3em;\n            height: 3em;\n            vertical-align: -0.125em;\n        }\n\t\t@keyframes rainbow-text-soft {\n\t\t  0% { color: #ff9999; }  /* Light Red */\n\t\t  14% { color: #ffcc99; } /* Light Orange */\n\t\t  28% { color: #ffff99; } /* Light Yellow */\n\t\t  42% { color: #ccff99; } /* Light Green */\n\t\t  57% { color: #99ccff; } /* Light Blue */\n\t\t  71% { color: #cc99ff; } /* Light Indigo */\n\t\t  85% { color: #ff99cc; } /* Light Violet */\n\t\t  100% { color: #ff9999; } /* Light Red */\n\t\t}\n\n\t\t.rainbow-text-soft {\n\t\t  animation: rainbow-text-soft 3s linear infinite;\n\t\t}\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
